title: PRECISE-IHCC Conference 2024
url: https://preciseihcc-conference.sg
favicon: /images/Logos/PRECISE_IHCC_Favicon_1.png
colors:
  primary-color: "#074877"
  secondary-color: "#6dc7e0"
  media-colors:
    - title: media-color-one
      color: "#f7d08a"
    - title: media-color-two
      color: "#f79f79"
    - title: media-color-three
      color: "#16095b"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#00838f"
description: Jointly organised by Precision Health Research, Singapore (PRECISE)
  and the International Health Cohorts Consortium (IHCC), the conference will
  bring together some 600 thought leaders, clinicians, scientists, biotechs, and
  patient advocacy associations from across the world who are at the forefront
  of precision medicine and public health innovation.
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://staging.dy7yrqfuaesd0.amplifyapp.com
prod: https://master.dy7yrqfuaesd0.amplifyapp.com
facebook-pixel: ""
shareicon: /images/Logos/precise-ihcc conference logo.png
is_government: false
google_analytics_ga4: G-7DR5WBKKPQ
linkedin-insights: ""
resources_name: logos
